// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_E14TOYINTERCHANGE_E14TOY_H_
#define FLATBUFFERS_GENERATED_E14TOYINTERCHANGE_E14TOY_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 12 &&
              FLATBUFFERS_VERSION_REVISION == 19,
             "Non-compatible flatbuffers version included");

namespace e14toy {

struct Pixel;

struct Display;

struct Message;
struct MessageBuilder;

enum class MessageId : int8_t {
  FullDisplay = 0
};

inline const MessageId (&EnumValuesMessageId())[1] {
  static const MessageId values[] = {
    MessageId::FullDisplay
  };
  return values;
}

inline const char * const *EnumNamesMessageId() {
  static const char * const names[2] = {
    "FullDisplay",
    nullptr
  };
  return names;
}

inline const char *EnumNameMessageId(MessageId e) {
  if (::flatbuffers::IsOutRange(e, MessageId::FullDisplay, MessageId::FullDisplay)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesMessageId()[index];
}

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) Pixel FLATBUFFERS_FINAL_CLASS {
 private:
  uint8_t r_;
  uint8_t g_;
  uint8_t b_;

 public:
  Pixel()
      : r_(0),
        g_(0),
        b_(0) {
  }
  Pixel(uint8_t _r, uint8_t _g, uint8_t _b)
      : r_(::flatbuffers::EndianScalar(_r)),
        g_(::flatbuffers::EndianScalar(_g)),
        b_(::flatbuffers::EndianScalar(_b)) {
  }
  uint8_t r() const {
    return ::flatbuffers::EndianScalar(r_);
  }
  uint8_t g() const {
    return ::flatbuffers::EndianScalar(g_);
  }
  uint8_t b() const {
    return ::flatbuffers::EndianScalar(b_);
  }
};
FLATBUFFERS_STRUCT_END(Pixel, 3);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(1) Display FLATBUFFERS_FINAL_CLASS {
 private:
  e14toy::Pixel content_[64];

 public:
  Display()
      : content_() {
  }
  Display(::flatbuffers::span<const e14toy::Pixel, 64> _content) {
    ::flatbuffers::CastToArray(content_).CopyFromSpan(_content);
  }
  const ::flatbuffers::Array<e14toy::Pixel, 64> *content() const {
    return &::flatbuffers::CastToArray(content_);
  }
};
FLATBUFFERS_STRUCT_END(Display, 192);

struct Message FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MessageBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_DISPLAY = 6
  };
  e14toy::MessageId id() const {
    return static_cast<e14toy::MessageId>(GetField<int8_t>(VT_ID, 0));
  }
  const e14toy::Display *display() const {
    return GetStruct<const e14toy::Display *>(VT_DISPLAY);
  }
  template <bool B = false>
  bool Verify(::flatbuffers::VerifierTemplate<B> &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_ID, 1) &&
           VerifyField<e14toy::Display>(verifier, VT_DISPLAY, 1) &&
           verifier.EndTable();
  }
};

struct MessageBuilder {
  typedef Message Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(e14toy::MessageId id) {
    fbb_.AddElement<int8_t>(Message::VT_ID, static_cast<int8_t>(id), 0);
  }
  void add_display(const e14toy::Display *display) {
    fbb_.AddStruct(Message::VT_DISPLAY, display);
  }
  explicit MessageBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Message> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Message>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Message> CreateMessage(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    e14toy::MessageId id = e14toy::MessageId::FullDisplay,
    const e14toy::Display *display = nullptr) {
  MessageBuilder builder_(_fbb);
  builder_.add_display(display);
  builder_.add_id(id);
  return builder_.Finish();
}

inline const e14toy::Message *GetMessage(const void *buf) {
  return ::flatbuffers::GetRoot<e14toy::Message>(buf);
}

inline const e14toy::Message *GetSizePrefixedMessage(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<e14toy::Message>(buf);
}

template <bool B = false>
inline bool VerifyMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifyBuffer<e14toy::Message>(nullptr);
}

template <bool B = false>
inline bool VerifySizePrefixedMessageBuffer(
    ::flatbuffers::VerifierTemplate<B> &verifier) {
  return verifier.template VerifySizePrefixedBuffer<e14toy::Message>(nullptr);
}

inline void FinishMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<e14toy::Message> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMessageBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<e14toy::Message> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace e14toy

#endif  // FLATBUFFERS_GENERATED_E14TOYINTERCHANGE_E14TOY_H_
